### ISSUE TITLE
Add me as a Nuget Package owner

### ISSUE THREAD

**Issue by cskardon** [cskardon/Neo4j.AspNet.Identity#9]
If possible (and you feel like it) could you add me as a co-owner to the Nuget Package so I can publish updates to the package as well?

(detailed here: https://docs.nuget.org/create/managing-package-owners)
Username: cskardon

Ta

**Comment by assimoes** [comment]
hello mate,

Is you nuget user cskardon?

**Comment by assimoes** [comment]
Hello Chris,

I've added you as a package owner on nuget for this project.

With regards to the project itself, you probably might have noticed that I've abandoned any development here since due to immense lack of time. With this out of the way, I've tried today to transfer this project's ownership to you, but since you have a fork with the same name I was unable to complete the transfer.

**Comment by cskardon** [comment]
Thanks buddy, I understand the time thing entirely, it's only as I was using something similar myself that I did the pull request :)

I've deleted my copy so feel free to transfer whenever, I'm happy either way!

**Comment by assimoes** [comment]
Yep, transfer is ongoing! :)
Thank you for making this project better :)

**Comment by cskardon** [comment]
Done! Thank you for starting it!
